site_name: iABC 学习资源

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 iABC'

nav:
# pages:
  - 主页: 'index.md'

  - 诗词题库:
    - '闯关答题': 'public/index.md'
    - '本周学习': 'public/todo.md'
    - '复习回顾': 'public/review.md'

  - 爱上古诗:
    - '乐学古诗': '爱上古诗/天乐学古诗.md'
    - '唐诗': '爱上古诗/唐诗.md'
    - '宋词': '爱上古诗/宋词.md'
    # - '乐府民歌': '爱上古诗/乐府民歌.md'
    # - '长诗10首': '爱上古诗/长诗10首.md'
    - '180首诗词': '爱上古诗/180首诗词.md'
    - '小学必背70首': '爱上古诗/小学必背70首.md'
    - '小学补充70首': '爱上古诗/小学补充70首.md'    
    
  - 少儿编程:
    - 'microbit': '少儿编程/microbit/index.md'

    - 'Tinkercad':
      - 'Codeblocks': '少儿编程/tinkercad_codeblocks/index.md'
      - 'Circuits': '少儿编程/tinkercad_circuits/index.md'

  - About: 'about.md'

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#   logo: 'images/favicon.ico'
  search:
    language: 'en, zh'
    tokenizer: '[\s\-\.]+'
  language: 'zh'

extra_css:
  - css/extra.css
